<!-- 例外処理を使うことができる
1. 例外
例外について

例外とは何か
何のためにあるのか
をプログラミング初心者にわかるように説明してください。 -->

# 例外とは何のためにあるのか？
プログラムの発生した 「**例外**」的な問題(予期せぬ問題)のこと

発生しない、または発生してはいけないエラーが**例外**です。

例えばスマホなどを使っていてたまに「予期せぬエラーが発生したのでアプリを終了します。」と出てアプリを強制終了することがあります。

あれは例外が発生したから起こるものです。

- 例外処理

例外、つまり予期せぬエラーが発生した時にそれをキャッチしてユーザーに何かしらのメッセージを表示するなどのことを指します。
以下はその例外処理のやり方と例です。

例:
```ruby
puts '計算してほしい数字を入力してください。'
i = gets.to_i

# beginの直下には例外が起こりうる処理を書く
# 例外が起きなければそのまま処理が行われensureに行きます。
begin
  puts 10 / i
  puts 'エラーはないので実行します。'

# rescueには例外が発生した場合の処理を書く
# => e とすると、変数eに格納された例外がなぜ起きたのか教えてくれます。
rescue => e
  puts 'エラーです！、これはユーザーに伝えるものです。'
  # 先程のエラーをエラーメッセージとして表示させます。
  puts e.message
  # 例外のオブジェクトの種類、つまりクラスの種類も表示してみます。
  puts e.class

# そして最後にensureは例外が起きても起きなくても実行したい処理を書きます。
ensure
  puts 'お疲れ様です'
end
```

```ruby
# 今回は'5'を渡してみます。
'計算してほしい数字を入力してください。'
5

# 出力結果
2
'お疲れ様です'
```

```ruby
# 次はエラーになる'0'を渡してみます。
'計算してほしい数字を入力してください。'
0

# 出力結果
エラーです！、これはユーザーに伝えるものです。
divided by 0
ZeroDivisionError
'お疲れ様です'
```

このような処理になります。